use super::CodeTokenKind;

#[derive(Debug, Clone, Copy)]
pub(super) struct AnsiTheme {
    pub(super) base: &'static str,
    pub(super) reset: &'static str,
    pub(super) string: &'static str,
    pub(super) number: &'static str,
    pub(super) keyword: &'static str,
    pub(super) comment: &'static str,
    pub(super) decorator: &'static str,
    pub(super) operator: &'static str,
    pub(super) property: &'static str,
    pub(super) variable: &'static str,
    pub(super) diff_add: &'static str,
    pub(super) diff_remove: &'static str,
    pub(super) diff_hunk: &'static str,
    pub(super) diff_meta: &'static str,
    pub(super) diff_file: &'static str,
    pub(super) diff_line_number: &'static str,
    pub(super) shell_prompt: &'static str,
    pub(super) shell_command: &'static str,
    pub(super) shell_flag: &'static str,
    pub(super) shell_path: &'static str,
    pub(super) shell_info: &'static str,
    pub(super) shell_success: &'static str,
    pub(super) shell_warning: &'static str,
    pub(super) shell_error: &'static str,
}

pub(super) const ANSI_THEME: AnsiTheme = AnsiTheme {
    reset: "\x1b[0m",
    base: "\x1b[38;2;220;220;220m",
    string: "\x1b[38;2;206;145;120m",
    number: "\x1b[38;2;181;206;168m",
    keyword: "\x1b[38;2;86;156;214m",
    comment: "\x1b[38;2;106;153;85m",
    decorator: "\x1b[38;2;78;201;176m",
    operator: "\x1b[38;2;212;212;212m",
    property: "\x1b[38;2;156;220;254m",
    variable: "\x1b[38;2;255;203;107m",
    diff_add: "\x1b[38;2;106;171;115m",
    diff_remove: "\x1b[38;2;206;102;102m",
    diff_hunk: "\x1b[38;2;97;175;239m",
    diff_meta: "\x1b[38;2;181;140;96m",
    diff_file: "\x1b[38;2;214;214;170m",
    diff_line_number: "\x1b[38;2;156;220;254m",
    shell_prompt: "\x1b[38;2;110;180;160m",
    shell_command: "\x1b[38;2;245;214;150m",
    shell_flag: "\x1b[38;2;137;196;244m",
    shell_path: "\x1b[38;2;156;220;254m",
    shell_info: "\x1b[38;2;120;170;220m",
    shell_success: "\x1b[38;2;120;190;130m",
    shell_warning: "\x1b[38;2;224;193;108m",
    shell_error: "\x1b[38;2;214;116;116m",
};

impl AnsiTheme {
    pub(super) fn color_for(&self, kind: CodeTokenKind) -> Option<&'static str> {
        match kind {
            CodeTokenKind::Plain => None,
            CodeTokenKind::String => Some(self.string),
            CodeTokenKind::Number => Some(self.number),
            CodeTokenKind::Keyword => Some(self.keyword),
            CodeTokenKind::Comment => Some(self.comment),
            CodeTokenKind::Decorator => Some(self.decorator),
            CodeTokenKind::Operator => Some(self.operator),
            CodeTokenKind::Property => Some(self.property),
            CodeTokenKind::Variable => Some(self.variable),
            CodeTokenKind::DiffAdded => Some(self.diff_add),
            CodeTokenKind::DiffRemoved => Some(self.diff_remove),
            CodeTokenKind::DiffHunk => Some(self.diff_hunk),
            CodeTokenKind::DiffMeta => Some(self.diff_meta),
            CodeTokenKind::DiffFile => Some(self.diff_file),
            CodeTokenKind::DiffLineNumber => Some(self.diff_line_number),
            CodeTokenKind::ShellPrompt => Some(self.shell_prompt),
            CodeTokenKind::ShellCommand => Some(self.shell_command),
            CodeTokenKind::ShellFlag => Some(self.shell_flag),
            CodeTokenKind::ShellPath => Some(self.shell_path),
            CodeTokenKind::ShellInfo => Some(self.shell_info),
            CodeTokenKind::ShellSuccess => Some(self.shell_success),
            CodeTokenKind::ShellWarning => Some(self.shell_warning),
            CodeTokenKind::ShellError => Some(self.shell_error),
        }
    }
}
