[package]
name = "yode-runtime"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
yode-core = { workspace = true }
yode-llm = { workspace = true }
yode-tools = { workspace = true }

[dev-dependencies]
tempfile = "3"
